
obj-$(CONFIG_MXC_MMA8451)       += mxc_mma8451.o
#obj-$(CONFIG_MXC_MMA8451)       += mxc_mma8452.o
#obj-$(CONFIG_GS_MMA8452) 	+= mma8452.o
obj-$(CONFIG_SENSORS_MAG3110)   += mag3110.o
#obj-$(CONFIG_MXC_MPL3115)       += mpl3115.o
obj-y +=hwmon.o

